// English NPC data pools — mirrors the structure of npcData.ts

export const FIRST_IMPRESSIONS_EN = [
  'Smiles warmly, but their eyes never stop scanning the room for exits.',
  'Comes across as welcoming and open — until someone mentions the past.',
  'Speaks slowly, as if every word has already been carefully weighed.',
  'Maintains an almost unnerving calm even when those around them grow agitated.',
  'Looks like someone who has seen too much but is still trying to do right.',
  'Charming on the surface, but always holding one truth back.',
  'Carries themselves like a noble even in worn clothes and muddy boots.',
  'Has a gaze that makes small lies feel dangerous.',
  'Seems helpful enough, but asks strangers slightly too precise questions.',
  'Comes across as practical, tired, and difficult to impress.',
]

export const MOTIVATIONS_EN = [
  'wants to reclaim a lost reputation before anyone discovers how far they truly fell.',
  'is searching for a missing relative who was officially declared dead.',
  'is trying to repay a debt to someone who should no longer be alive.',
  'wants to protect a small circle of people, even if it means telling lies.',
  'collects information because knowledge is the only currency that never fails.',
  'is searching old letters, temple records, and harbour lists for one specific name.',
  'needs to leave town before the next new moon but lacks help with the final step.',
  'wants revenge while still trying to convince themselves it is really about justice.',
  'wants the adventurers to solve a problem without understanding who truly benefits.',
  'is trying to keep a fragile peace agreement alive even though both sides despise each other.',
]

export const SECRETS_EN = [
  'sold information to a rival in order to save a close friend.',
  'is using a false name and dreads meeting anyone from their old life.',
  'was the last person to see the missing priest alive.',
  "carries a small magical item that slowly changes its owner's dreams.",
  'owes money to a smuggler captain who will be coming to collect very soon.',
  'knows where the body is buried, but not who put it there.',
  'was once a member of the very organisation they now warn others about.',
  'receives unsigned letters that always predict exactly one detail correctly.',
  'let an innocent person take the blame for something they were involved in.',
  'is not as devout, poor, wealthy, loyal, or innocent as they pretend to be.',
  'stole a sacred relic and hid it somewhere no one dares to search.',
  'has a child that no one in town must know exists.',
  'works as an informant for an enemy faction.',
  'forged their noble papers and lives on borrowed status.',
  'can identify the leader of a local cult but dares not speak the name aloud.',
  'once made a pact that is still demanding payment.',
  'saw the town watch murder an innocent person in an alley.',
  'keeps a key to a room that officially does not exist.',
  'has a twin who uses their name for dangerous purposes.',
  'was paid to stay silent about a vanished caravan.',
  'has no memory of one specific night and fears the truth.',
  'keeps a monster hidden because it once saved their life.',
  'stole from the temple, but only to save a sick relative.',
  'knows that a local prophecy was deliberately altered.',
  'is in love with someone they publicly condemn.',
  'changed sides in a war and hides the old marks on their body.',
  "buried a treasure, but the map is tattooed on a dead man's skin.",
  'hears a voice from the well every night and answers it.',
  'sold false medicine that may have cost someone their life.',
  'possesses a letter that could ruin a powerful family.',
  'promised away their soul but does not know to whom.',
  'has hidden a fugitive in the cellar for weeks.',
  'killed in self-defense, but the evidence tells another story.',
  'carries a curse that only reveals itself under the full moon.',
  "accepted money to sabotage the town's defenses.",
  'knows a secret route into the castle.',
  'swapped a newborn child many years ago.',
  'has been impersonating a dead hero.',
  'has demonic ancestry their family tried to conceal.',
  'hid the truth about a fire that destroyed an entire district.',
  'has died once and remembers something from the other side.',
  'can read a forbidden language but claims otherwise.',
  'stole the identity of a traveller who never reached their destination.',
  'helped pirates find safe harbours.',
  'has a magical illness that slowly changes their shadow.',
  'promised the same inheritance to two different people.',
  'buried a murder accusation by bribing witnesses.',
  'saw an angel fall and was paid to call it a meteor.',
  'has a map of the undercity sewn into their cloak lining.',
  'stole a name from a fey and is still paying the price.',
  "has proof that the town's saint never existed.",
  'is secretly married to someone from an enemy family.',
  'has an old war wound that did not come from the war they describe.',
  'keeps a living prisoner everyone else believes is dead.',
  'knows the next festival will be used as cover for a coup.',
  'had their memories altered and is beginning to notice the gaps.',
  "sold a child's name to a witch.",
  'sent innocent adventurers to their deaths to protect themselves.',
  'has a hidden entrance to the sewers beneath their floorboards.',
  'has promised to betray the players if a specific person gives the signal.',
  'keeps a chest of letters from people who should be dead.',
  'has seen a dragon in human form and recognizes its eyes.',
  'has hidden a weapon capable of killing their own protector.',
  'deceived a divine servant and is waiting for the consequence.',
  'has a sick mentor who demands increasingly dangerous ingredients.',
  'wrote a confession but hid it with someone they do not trust.',
  'survived a cult ceremony and bears the mark beneath their clothes.',
  'knows the local ruler is a doppelganger.',
  'pawned something that did not belong to them.',
  'lied about being the last survivor of their village.',
  'stole an egg from a very dangerous nest.',
  'betrayed a friend to gain access to magical training.',
  'owns a mirror that shows the future they are trying to avoid.',
  'has a hidden tattoo that functions as the key to a seal.',
  'sold weapons to both sides of a conflict.',
  'has fed a local legend with false rumours for years.',
  "hid a priest's diary because it mentions their name.",
  'swore to protect someone they secretly hate.',
  'has a scar from a ritual that was never completed.',
  'broke a magical seal and convinced everyone it still works.',
  'saw a family member turn into something inhuman.',
  'owes a debt to a tavern keeper that cannot be paid with money.',
  'exchanged memories with a stranger in order to survive.',
  'buried a pouch of coins alongside a false corpse.',
  'keeps secret correspondence with an enemy of the town.',
  'saw a child perform miracles and kept it hidden.',
  'lied about the extent of their magical ability.',
  'hides the symbol of a forbidden order in their boot.',
  'survived by informing on a group of refugees.',
  'knows the true version of a song bards only know as myth.',
  'has forgotten their real name but reacts to it in dreams.',
  'stole a key from a tomb that now stands open.',
  'broke their oath but is searching for a way to atone.',
  'has a treasure hidden in plain sight that no one dares touch.',
  'found a corpse that looks exactly like them.',
  'received an invitation to a party that happened a hundred years ago.',
  'bound their fate to an animal that has now disappeared.',
  'hid the truth about why the bridge collapsed.',
  'has a secret that can only be spoken in a language they no longer dare use.',

]

export const MANNERISMS_EN = [
  'constantly twists a ring whenever the conversation approaches the truth.',
  'lowers their voice when lying but speaks louder when frightened.',
  'adjusts a cuff even when the clothes are far too threadbare for such refinement.',
  'silently counts on their fingers before answering a difficult question.',
  'never looks directly at the person they are actually talking to.',
  'uses people\'s full names whenever they want control of the conversation.',
  'knocks twice on the table whenever mentioning something supernatural.',
  'always smiles exactly one second too late.',
  'picks up small objects and sets them back down in perfect order.',
  'ends almost every sentence with a question, even when giving orders.',
]

export const RELATION_TARGETS_EN = [
  'a retired adventurer',
  'the town\'s tax collector',
  'a jealous rival from the same guild',
  'a smuggler with impeccable manners',
  'a temple warden with a guilty conscience',
  'a tavern keeper who hears more than they let on',
  'a young apprentice with dangerous ambitions',
  'a noble family that would rather forget them',
  'a captain who never sails without a hidden cargo',
  'an old friend now working for the enemy',
]

export const RELATION_VERBS_EN = [
  'owes their life to',
  'is being blackmailed by',
  'secretly protects',
  'suspects of treachery',
  'loves but cannot admit it to',
  'has sworn revenge against',
  'receives secret messages from',
  'has stolen something precious from',
]

export const SCENE_HOOKS_EN = [
  'If the players help, they receive a name, a location, and a dangerous deadline.',
  'If they press too hard, the NPC shuts down completely and sends someone after them later.',
  'A wrong question makes the NPC believe the players already know too much.',
  'The NPC offers help but asks for a small favour that turns out to be morally murky.',
  'A third party is watching the conversation and reacts when the players leave.',
  'The NPC needs a quick decision, not a long plan.',
  'The truth is useful, but speaking it aloud would harm an innocent person.',
  'The NPC could become a powerful ally — but only if the players treat them as a person first.',
]
