// RoleSmith-inspired NPC layer for Fantasy RPG Generator v2.
// The goal is not a full stat block first, but a playable NPC in 30 seconds.

export const FIRST_IMPRESSIONS = [
  'Smiler venligt, men øjnene scanner hele tiden rummet efter udgange.',
  'Virker varm og imødekommende, indtil nogen nævner fortiden.',
  'Taler roligt, som om hvert ord allerede er blevet vejet på en guldvægt.',
  'Har en næsten irriterende ro, selv når andre bliver ophidsede.',
  'Ligner en person, der har set for meget, men stadig prøver at være ordentlig.',
  'Er charmerende på overfladen, men holder altid én sandhed tilbage.',
  'Bærer sig som en adelig, selv i slidt tøj og mudrede støvler.',
  'Har et blik, der får små løgne til at føles farlige.',
  'Virker hjælpsom, men spørger lidt for præcist ind til fremmede.',
  'Giver indtryk af at være praktisk, træt og svær at imponere.',
]

export const MOTIVATIONS = [
  'vil genvinde et tabt ry, før nogen opdager hvor dybt faldet egentlig var.',
  'leder efter en forsvundet slægtning, som officielt blev erklæret død.',
  'prøver at betale en gæld til nogen, der ikke længere burde være i live.',
  'vil beskytte sin lille kreds af folk, selv hvis det kræver løgne.',
  'samler oplysninger, fordi viden er den eneste valuta, der altid virker.',
  'søger et bestemt navn i gamle breve, tempelbøger og havnelister.',
  'vil ud af byen før næste nymåne, men mangler hjælp til det sidste skridt.',
  'ønsker hævn, men forsøger stadig at bilde sig selv ind, at det handler om retfærdighed.',
  'vil have eventyrerne til at løse et problem uden at forstå, hvem der egentlig får gavn af det.',
  'prøver at holde en skrøbelig fredsaftale i live, selv om begge sider hader hinanden.',
]

export const SECRETS = [
  'har solgt information til en rival for at redde en nær ven.',
  'bruger et falsk navn og frygter at møde nogen fra sit gamle liv.',
  'er den sidste person, der så den forsvundne præst i live.',
  'har en lille magisk genstand, som langsomt ændrer ejerens drømme.',
  'skylder penge til en smuglerkaptajn, der snart kommer for at hente dem.',
  'ved hvor liget er begravet, men ikke hvem der lagde det der.',
  'har engang været medlem af den organisation, de nu advarer imod.',
  'modtager breve uden afsender, som altid forudsiger én detalje korrekt.',
  'lod en uskyldig tage skylden for noget, de selv var involveret i.',
  'er ikke så from, fattig, rig, loyal eller uskyldig, som de lader som om.',
  'har stjålet en hellig relikvie og gemt den et sted, hvor ingen tør lede.',
  'har et barn, som ingen i byen må vide eksisterer.',
  'arbejder som informant for en fjendtlig fraktion.',
  'har forfalsket sit adelsbrev og lever på lånt status.',
  'kan genkende lederen af en lokal kult, men tør ikke sige navnet højt.',
  'har engang indgået en pagt, som stadig kræver betaling.',
  'har set byens vogter myrde en uskyldig i en gyde.',
  'gemmer en nøgle til et rum, som officielt ikke findes.',
  'har en tvilling, som bruger deres navn til noget farligt.',
  'blev betalt for at tie om en forsvunden karavane.',
  'har mistet hukommelsen om én bestemt nat og frygter sandheden.',
  'holder et monster skjult, fordi det engang reddede deres liv.',
  'har stjålet fra templet, men kun for at redde en syg slægtning.',
  'ved at en lokal profeti er blevet ændret med vilje.',
  'er forelsket i en person, de offentligt fordømmer.',
  'har skiftet side i en krig og skjuler de gamle mærker på kroppen.',
  'har begravet en skat, men kortet er tatoveret på en død mands hud.',
  'kan høre en stemme fra brønden hver nat og svarer den tilbage.',
  'har solgt falsk medicin, som måske har kostet nogen livet.',
  'har et brev, der kan vælte en magtfuld familie.',
  'har lovet sin sjæl væk, men ved ikke til hvem.',
  'har skjult en flygtning i kælderen i flere uger.',
  'har dræbt i selvforsvar, men beviserne siger noget andet.',
  'har en forbandelse, der kun viser sig ved fuldmåne.',
  'har modtaget penge for at sabotere byens forsvar.',
  'kender en hemmelig vej ind i borgen.',
  'har byttet et spædbarn for mange år siden.',
  'har udgivet sig for at være en død helt.',
  'har en dæmonisk arv, som familien har forsøgt at skjule.',
  'har skjult sandheden om en brand, der ødelagde et helt kvarter.',
  'har været død én gang og husker noget fra den anden side.',
  'kan læse et forbudt sprog, men påstår ikke at kunne.',
  'har stjålet en identitet fra en rejsende, der aldrig nåede frem.',
  'har hjulpet pirater med at finde sikre havne.',
  'har en magisk sygdom, der langsomt ændrer deres skygge.',
  'har lovet to forskellige personer den samme arv.',
  'har skjult en mordanklage ved at bestikke vidner.',
  'har set en engel falde, men blev betalt for at kalde det et meteornedslag.',
  'har et kort over underbyen syet ind i foret på sin kappe.',
  'har stjålet et navn fra en fey og betaler stadig prisen.',
  'har beviser for at byens helgen aldrig eksisterede.',
  'er i hemmelighed gift med nogen fra en fjendtlig familie.',
  'har en gammel krigsskade, der ikke kom fra den krig de fortæller om.',
  'har gemt en levende fange, som alle tror er død.',
  'ved at den næste festival bliver brugt som dække for et kup.',
  'har fået sine minder ændret og begynder at opdage hullerne.',
  'har solgt et barns navn til en heks.',
  'har sendt uskyldige eventyrere i døden for at beskytte sig selv.',
  'har en hemmelig indgang til kloakkerne under sit gulv.',
  'har lovet at forråde spillerne, hvis en bestemt person giver signalet.',
  'har en kiste med breve fra folk, der burde være døde.',
  'har set en drage i menneskeskikkelse og genkender dens øjne.',
  'har skjult et våben, som kan dræbe deres egen beskytter.',
  'har bedraget en guddoms tjener og venter på konsekvensen.',
  'har en syg mentor, som kræver stadig farligere ingredienser.',
  'har skrevet en tilståelse, men gemt den hos en person de ikke stoler på.',
  'har overlevet en kultceremoni og bærer mærket under tøjet.',
  'ved at den lokale hersker er en dobbeltgænger.',
  'har pantsat noget, der ikke tilhørte dem.',
  'har løjet om at være den sidste overlevende fra sin landsby.',
  'har stjålet et æg fra en meget farlig rede.',
  'har forrådt en ven for at få adgang til magisk undervisning.',
  'har et spejl, der viser den fremtid de prøver at undgå.',
  'har en skjult tatovering, som fungerer som nøgle til et segl.',
  'har solgt våben til begge sider af en konflikt.',
  'har i årevis fodret en lokal legende med falske rygter.',
  'har gemt en præsts dagbog, fordi den nævner deres navn.',
  'har svoret at beskytte en person, de egentlig hader.',
  'har et ar fra et ritual, der aldrig blev afsluttet.',
  'har ødelagt et magisk segl og bildt alle ind, at det stadig virker.',
  'har set et familiemedlem blive til noget umenneskeligt.',
  'har en gæld til en kroejer, som ikke kan betales med penge.',
  'har byttet minder med en fremmed for at overleve.',
  'har begravet en pose mønter sammen med et falsk lig.',
  'har en hemmelig korrespondance med en fjende af byen.',
  'har set et barn udføre mirakler og holdt det skjult.',
  'har løjet om sit niveau af magisk kunnen.',
  'har gemt et symbol fra en forbudt orden i sin støvle.',
  'har overlevet ved at angive en gruppe flygtninge.',
  'har en sand version af en sang, som barder kun kender som myte.',
  'har glemt sit rigtige navn, men reagerer på det i drømme.',
  'har stjålet en nøgle fra en grav, der nu står åben.',
  'har forrådt sin ed, men leder efter en måde at gøre bod på.',
  'har en skat gemt i plain sight som ingen tør røre.',
  'har fundet et lig, der ligner dem selv.',
  'har modtaget en invitation til et selskab, der fandt sted for hundrede år siden.',
  'har bundet sin skæbne til et dyr, der nu er forsvundet.',
  'har gemt sandheden om hvorfor broen styrtede sammen.',
  'har en hemmelighed, der kun kan siges på et sprog, de ikke længere tør tale.',

]

export const MANNERISMS = [
  'drejer konstant en ring, når samtalen nærmer sig sandheden.',
  'sænker stemmen, når de lyver, men taler højere når de er bange.',
  'retter på manchetten, selv når tøjet er alt for slidt til den slags.',
  'tæller lydløst på fingrene, før de svarer på svære spørgsmål.',
  'ser aldrig direkte på den person, de egentlig taler til.',
  'bruger folks fulde navn, når de vil have kontrol over samtalen.',
  'banker to gange på bordet, når de nævner noget overnaturligt.',
  'smiler altid et sekund for sent.',
  'samler småting op og lægger dem tilbage i perfekt orden.',
  'afslutter næsten hver sætning med et spørgsmål, selv når de giver ordrer.',
]

export const RELATION_TARGETS = [
  'en pensioneret eventyrer',
  'byens skatteopkræver',
  'en jaloux rival fra samme laug',
  'en smugler med alt for gode manerer',
  'en tempelvogter med dårlig samvittighed',
  'en kroejer, der hører mere end han siger',
  'en ung lærling med farlige ambitioner',
  'en adelig familie, der helst vil glemme dem',
  'en kaptajn, som aldrig sejler uden hemmelig last',
  'en gammel ven, der nu arbejder for fjenden',
]

export const RELATION_VERBS = [
  'skylder sit liv til',
  'bliver afpresset af',
  'beskytter i hemmelighed',
  'mistænker for forræderi',
  'elsker, men tør ikke indrømme det over for',
  'har svoret hævn mod',
  'modtager hemmelige beskeder fra',
  'har stjålet noget vigtigt fra',
]

export const SCENE_HOOKS = [
  'Hvis spillerne hjælper, får de et navn, et sted og en farlig tidsfrist.',
  'Hvis de presser for hårdt, lukker NPC’en helt ned og sender nogen efter dem senere.',
  'Et forkert spørgsmål får NPC’en til at tro, at spillerne allerede ved for meget.',
  'NPC’en tilbyder hjælp, men beder om en lille tjeneste, der viser sig at være moralsk grumset.',
  'En tredje part overvåger samtalen og reagerer, når spillerne forlader stedet.',
  'NPC’en har brug for en hurtig beslutning, ikke en lang plan.',
  'Sandheden er nyttig, men den skader en uskyldig, hvis den bliver sagt højt.',
  'NPC’en kan blive en stærk allieret, men kun hvis spillerne behandler dem som et menneske først.',
]

export const PORTRAIT_PROMPT_NOTES = [
  'keep the face readable and emotionally specific',
  'show a lived-in costume with one memorable personal detail',
  'avoid generic fantasy model posing; make the stance reveal personality',
  'cinematic natural light, practical materials, grounded expression',
  'slightly imperfect, story-rich, useful as an NPC portrait at the table',
]
